# native-helper-graalvm generation configuration
---
# the output file
reflectConfigJsonOutputPath: src/main/resources/META-INF/native-image/reflect-config.json
# will create subfolders for reflectConfigJsonOutputPath if they do not exists
createParentDirectory: true
# list of entries to generate
generate:
  # configure each class in a separate way
  - className: org.fugerit.java.nhg.reflect.config.Entry
    mode: getters
  - className: org.fugerit.java.nhg.reflect.config.EntryCondition
    mode: getters
  - className: org.fugerit.java.nhg.reflect.config.EntryField
    mode: getters
  - className: org.fugerit.java.nhg.reflect.config.EntryMethod
    mode: getters
  # read and configure all classes in the package
  - packageName: org.fugerit.java.nhg.config.model
    mode: getters_setters
    typeReachable: org.fugerit.java.nhg.config.NativeHelperFacade