# native-helper-graalvm generation configuration
---
reflectConfigJsonOutputPath: src/main/resources/META-INF/native-image/reflect-config.json
createParentDirectory: true
generate:
  - className: org.fugerit.java.nhg.reflect.config.Entry
    mode: getters
  - className: org.fugerit.java.nhg.reflect.config.EntryCondition
    mode: getters
  - className: org.fugerit.java.nhg.reflect.config.EntryField
    mode: getters
  - className: org.fugerit.java.nhg.reflect.config.EntryMethod
    mode: getters
  - packageName: org.fugerit.java.nhg.config.model
    mode: getters_setters
    typeReachable: org.fugerit.java.nhg.config.NativeHelperFacade